### PR TITLE
Fixed manifest.webapp for serviceworker permission

### PR DESCRIPTION
**Pull request by sunsetsonwheels**
Push notifications could be working now.

### CODE REVIEW

**Comment by ixzzd** [comment]
thank you!

**Comment by ixzzd** [comment]
@jkelol111  does it work for you? i am receiving notification only if telegram is working in background

**Comment by ixzzd** [comment]
i am on GerdaOS (firmware v13)

**Comment by sunsetsonwheels** [comment]
I will test it later on my v16 device, but from what I've seen in the KaiOS Simulator, there is no more 'No push notifications ' warning thrown from `app.js` in the JavaScript console.

**Comment by sunsetsonwheels** [comment]
A.k.a the notification service worker seems to register and install just fine.

**Pull request merged**
